# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: test
          command: ls -ls
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  static-analysis:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Static Code Analysis
          command: npm run test:static

  unit-tests:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Static Code Analysis
          command: npm run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - static-analysis:
          requires:
            - build
      - unit-tests:
          requires:
            - build      
